### ISSUE TITLE
Document code

### ISSUE THREAD

**Issue by zhang96716** [illidanlab/Simulator#13]
Hello, is the code you released complete? In the process of "mapped"_ matrix_ int.pkl "File import, is this the file you have pre trained before? If I make up a simulated data, I use run_ How should I deal with this fake data format when running ca2c.py without error? We look forward to your reply!

**Comment by KaixiangLin** [comment]
Please refer to the wiki here: https://github.com/illidanlab/Simulator/wiki  for the explanation of this matrix. It is MxN Size matrix indicating the valid grids.   Its value relies on the topology of your map.

**Comment by zhang96716** [comment]
Can you give me the pre training code file for this project? I have applied for the data set, and I promise that I will quote your paper in any work in the future

**Comment by KaixiangLin** [comment]
This is not a pre-trained file. It's a M by N matrix. If you are using different map or different region in the city or using different way to discretize the city.  This file is different. 

A bit more explanation:
This simulator is based on grid world. If you want to use it with map, the first step is to split the map into hexagonal/quadrilateral grids and then map it into a matrix. [mapped_matrix_int](https://github.com/illidanlab/Simulator/blob/d99e2b1352a1697e5930f9b45c4704db97e33f8f/simulator/envs.py#L31)

**Comment by zhang96716** [comment]
Thank you for your reply. Is your code complete? Now I'm trying to reproduce your paper. I have got the open data set of didi company, but when I print the map data as a matrix, the program has been unable to recognize my data pattern. Can you give me your data processing method? I really want to reproduce this paper, so that more people can quote this paper. If it's convenient, can I add a contact information for you? We look forward to your reply!

**Comment by TronYY** [comment]
> Thank you for your reply. Is your code complete? Now I'm trying to reproduce your paper. I have got the open data set of didi company, but when I print the map data as a matrix, the program has been unable to recognize my data pattern. Can you give me your data processing method? I really want to reproduce this paper, so that more people can quote this paper. If it's convenient, can I add a contact information for you? We look forward to your reply!

Have you solved the problem? It seems not easy to preprocess the raw data. I am even not allowed to apply for the data................

**Comment by TronYY** [comment]
> 

![](https://s2.loli.net/2021/12/22/a1zpfdFU5tqGrJb.png)

Hi！ Could you share the data with me? thx a lot!
