### ISSUE TITLE
Simulator

### ISSUE THREAD

**Issue by Tom7317** [illidanlab/Simulator#14]
Hello, how does the simulation experiment sample from the sample? How is the specific process achieved? How did the total number of drivers and the number of orders increase?

**Comment by KaixiangLin** [comment]
Hi, 
Please refer to [wiki]( https://github.com/illidanlab/Simulator/wiki) to see the simulator logic and data format. 
and also section 5 in the [paper](https://dl.acm.org/doi/pdf/10.1145/3219819.3219993)
