### ISSUE TITLE
state for any agent

### ISSUE THREAD

**Issue by seanguo61** [illidanlab/Simulator#2]
in this paper, for any agent i where s_t^i =[s_t, g_j]
here, s_t^i is a small state matrix or something else?

**Comment by KaixiangLin** [comment]
In the paper, s_t is defined as 
``` the spatial distributions of available vehicles and orders (i.e. the number of available vehicles and orders in each grid) and current time t (using one-hot encoding).```

In this code, s_t^i is not explicitly constructed while it can be constructed from state at [here](https://github.com/illidanlab/Simulator/blob/ede00b5a9f45e10bb58e1b80039a789243b9d760/tests/run_example.py#L67)

**Comment by seanguo61** [comment]
That is, s_t^i is the number of available vehicles and orders in a specific grid?
sorry to bother you, I have some trouble when I use DQN based on this simulator, could you please give me your DQN code about this paper. If it's inconvenient, please ignore my request .
Anyway, thank you a lot for your answer🙏🙏.

**Comment by KaixiangLin** [comment]
s_t contains # of vehicles, orders and time. I will release the alg code this weekend.

**Comment by seanguo61** [comment]
Thanks
