### ISSUE TITLE
fleet routing on a map

### ISSUE THREAD

**Issue by papyr** [illidanlab/Simulator#3]
hi, can you help with using this and fleet routing on a map

**Comment by KaixiangLin** [comment]
Hi, papyr, 

This simulator is based on grid world. If you want to use it with map, the first step is to split the map into hexagonal/quadrilateral grids and then map it into a matrix. [mapped_matrix_int](https://github.com/illidanlab/Simulator/blob/d99e2b1352a1697e5930f9b45c4704db97e33f8f/simulator/envs.py#L31)
