### ISSUE TITLE
How to let the simulator train real-order data of different days

### ISSUE THREAD

**Issue by kingchiuoy** [illidanlab/Simulator#5]
It seems like the generated time of each real-order in real-order data is between 0 - 143, how can I import data of different day in to the simulator to let it train different day's data in different episode?

**Comment by KaixiangLin** [comment]
The current simulator only supports sampling from a large set of orders and construct one-days' samples. 

To train different days' data in different episodes,  one way is to override the [self.utility_bootstrap_oneday_order()](https://github.com/illidanlab/Simulator/blob/d99e2b1352a1697e5930f9b45c4704db97e33f8f/simulator/envs.py#L261) in [reset_clean](https://github.com/illidanlab/Simulator/blob/d99e2b1352a1697e5930f9b45c4704db97e33f8f/simulator/envs.py#L242) method, and load one day's data into [self.day_orders](https://github.com/illidanlab/Simulator/blob/d99e2b1352a1697e5930f9b45c4704db97e33f8f/simulator/envs.py#L443)
