### ISSUE TITLE
Input and test

### ISSUE THREAD

**Issue by zhang96716** [illidanlab/Simulator#7]
Hello, can you tell me the data input and output of your simulator? Or can you give me a fake D data form? thank you

**Comment by KaixiangLin** [comment]
Hi, 

Please find the input format at here: https://github.com/illidanlab/Simulator/wiki

**Comment by zhang96716** [comment]
Can you comment some code

**Comment by KaixiangLin** [comment]
Please find testing code at https://github.com/illidanlab/Simulator/blob/master/tests/run_example.py
