### ISSUE TITLE
add new charging event into simulator

### ISSUE THREAD

**Issue by sihongho** [illidanlab/Simulator#8]
Hi Kaixiang,

If I want to add a new type of event "charing" into the simulator, do you have any suggestions about this modification?

thank you so much!

**Comment by KaixiangLin** [comment]
Hi, @SihongHo, I am not sure what are the functionalities of "charging" event, could you please elaborate?

**Comment by sihongho** [comment]
thank you @KaixiangLin , charging event contains two parts: 1. idle cars turn to low-energy status so they can not serve next order and need to go to a gas station/charging station. 2. low-energy cars arrive at a station and stay for a while then leave the station.

**Comment by KaixiangLin** [comment]
For making idle cars cannot serve next round, you can refer to this [function](https://github.com/illidanlab/Simulator/blob/d99e2b1352a1697e5930f9b45c4704db97e33f8f/simulator/objects.py#L381),  which set idle cars offline. 

As for arriving at a station, current this simulator only support gridwise operation. The minimal unit to distinguish location is grid. Maybe you can set one grid as station and change cars' location to that grid after setting it to "low-energy" state.
